name: Build and Deploy

on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Clean Install dependency and Build
      run:
        npm install
        rm -rf dist
        npm run build
        
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}  
        base_href: /angular-deloy-actions/
        deploy_branch: gh-pages # The branch the action should deploy to.
        angular_dist_build_folder: ./dist/angular-deloy-actions # The folder the action should deploy.
        angular_project_dir: angular-deloy-actions
