name: Build and Deploy

on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Clean Install dependency and Build
      run:
        npm install
        rm -rf dist
        
    - name: Angular Deploy gh-pages Actions
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.1
      with:
        github_access_token: ${{ secrets.ACCESS_TOKEN }}
        base_href: /angular-deloy-actions/
        deploy_branch: build_project # The branch the action should deploy to.
        angular_dist_build_folder: dist/angular-deploy-gh-actions # The folder the action should deploy.
