name: Build and Deploy

on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Clean Install dependency and Build
      run:
        npm install
        rm -rf dist
        npm run build
        
    - name: Deploy
      uses: Thonguyennt/angular-deloy-actions@3.7.1
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}  
        BRANCH: gh-pages
        
